// apps/demo-react/resources/js/components/ui/BigNumber.tsx
import React from "react";
import { cn } from "./cn";

/** Large numeral — size it at the call site (text-5xl, text-7xl, …). */
const BigNumber: React.FC<React.HTMLAttributes<HTMLSpanElement>> = ({
    className,
    ...rest
}) => (
    <span
        className={cn(
            "font-semibold tracking-tight tabular-nums text-white",
            className,
        )}
        {...rest}
    />
);

export default BigNumber;

// apps/demo-svelte/resources/js/components/ui/BigNumber.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import type { HTMLAttributes } from "svelte/elements";
    import { cn } from "./cn";

    interface Props extends HTMLAttributes<HTMLSpanElement> {
        children?: Snippet;
    }

    let { children, class: className, ...rest }: Props = $props();
</script>

<!-- Large numeral — size it at the call site (text-5xl, text-7xl, …). -->
<span
    {...rest}
    class={cn("font-semibold tracking-tight tabular-nums text-white", className)}
>
    {@render children?.()}
</span>
