// apps/demo-react/resources/js/mesh/Wire/PriceWatcher/index.tsx
import React, { useEffect, useState } from "react";
import { useWire } from "@mesh/react";
import { BigNumber, Button, Panel } from "@/components/ui";
import Sparkline from "@/components/demo/Wire/Sparkline";

interface PriceWatcherProps {
    symbol: string;
    initialPrice: number;
}

const MAX_POINTS = 40;

const PriceWatcher: React.FC<PriceWatcherProps> = ({ symbol, initialPrice }) => {
    const wire = useWire();

    const [history, setHistory] = useState<number[]>([initialPrice]);
    const [paused, setPaused] = useState(false);

    // Inbound: the server owns `price` — every change it makes flows
    // through $watch into local React state.
    useEffect(() => {
        wire.$watch("price", (value: number) => {
            setHistory((prev) => [...prev, value].slice(-MAX_POINTS));
        });
    }, [wire]);

    // Outbound: all React does is schedule the next server-side tick.
    // The interval is cleared on unmount (and while paused).
    useEffect(() => {
        if (paused) return;
        const id = window.setInterval(() => {
            void wire.$call("tick");
        }, 2000);
        return () => window.clearInterval(id);
    }, [wire, paused]);

    const price = history[history.length - 1];
    const previous = history.length > 1 ? history[history.length - 2] : null;
    const direction = previous === null ? null : price >= previous ? "up" : "down";
    const delta = previous === null ? 0 : price - previous;

    return (
        <Panel>
            <div className="flex flex-wrap items-start justify-between gap-4">
                <div>
                    <p className="k k--caps text-ink-3">
                        {symbol} · server-side random walk
                    </p>
                    <div className="mt-1 flex items-baseline gap-3">
                        {/* Key by history length so each server tick re-renders a fresh node */}
                        <BigNumber key={history.length} className="text-4xl">
                            ${price.toFixed(2)}
                        </BigNumber>
                        {direction !== null && (
                            <span className="font-mono text-sm tabular-nums text-ink-2">
                                <span aria-hidden="true">
                                    {direction === "up" ? "▲" : "▼"}
                                </span>
                                <span className="sr-only">
                                    {direction === "up" ? "Up" : "Down"}
                                </span>{" "}
                                {Math.abs(delta).toFixed(2)}
                            </span>
                        )}
                    </div>
                </div>

                <div className="flex items-center gap-4">
                    <span className="core-status">
                        <span
                            className="core-dot"
                            data-state={paused ? "off" : "live"}
                            aria-hidden="true"
                        />
                        {paused ? "Paused" : "Every 2s"}
                    </span>
                    <Button
                        variant="secondary"
                        size="sm"
                        onClick={() => setPaused((p) => !p)}
                        aria-pressed={paused}
                    >
                        {paused ? "Resume ticks" : "Pause ticks"}
                    </Button>
                </div>
            </div>

            <Sparkline
                className="mt-6"
                values={history}
                direction={direction}
                ariaLabel={`Sparkline of the last ${history.length} prices for ${symbol}`}
            />

            {/* Dimension line spanning the plot: how many ticks it holds. */}
            <div className="mt-2 pl-14">
                <div className="core-dim">
                    <span>
                        {history.length} of {MAX_POINTS} points
                    </span>
                </div>
            </div>

            <p className="mt-4 text-xs leading-relaxed text-ink-3">
                <code className="core-code">wire.$call("tick")</code> every 2s.{" "}
                <code className="core-code">wire.$watch("price", …)</code>{" "}
                streams each change back.
            </p>
        </Panel>
    );
};

export default PriceWatcher;

// apps/demo-vue/resources/js/mesh/Wire/PriceWatcher/index.vue
<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import { useWire } from "@mesh/vue";
import { BigNumber, Button, Panel } from "@/components/ui";
import Sparkline from "@/components/demo/Wire/Sparkline.vue";

interface PriceWatcherProps {
    symbol: string;
    initialPrice: number;
}

const props = defineProps<PriceWatcherProps>();

const MAX_POINTS = 40;

const wire = useWire();

const history = ref<number[]>([props.initialPrice]);
const paused = ref(false);

// Inbound: the server owns `price` — every change it makes flows
// through $watch into local Vue state.
const unwatchPrice = wire.$watch("price", (value: number) => {
    history.value = [...history.value, value].slice(-MAX_POINTS);
});

// Outbound: all Vue does is schedule the next server-side tick.
// The interval is cleared on unmount (and while paused).
let intervalId: number | null = null;

const stopTicking = () => {
    if (intervalId !== null) {
        window.clearInterval(intervalId);
        intervalId = null;
    }
};

const startTicking = () => {
    stopTicking();
    intervalId = window.setInterval(() => {
        void wire.$call("tick");
    }, 2000);
};

onMounted(startTicking);
watch(paused, (isPaused) => (isPaused ? stopTicking() : startTicking()));

onUnmounted(() => {
    stopTicking();
    unwatchPrice();
});

const price = computed(() => history.value[history.value.length - 1]);
const previous = computed(() =>
    history.value.length > 1 ? history.value[history.value.length - 2] : null,
);
const direction = computed(() =>
    previous.value === null ? null : price.value >= previous.value ? "up" : "down",
);
const delta = computed(() => (previous.value === null ? 0 : price.value - previous.value));
</script>

<template>
    <Panel>
        <div class="flex flex-wrap items-start justify-between gap-4">
            <div>
                <p class="k k--caps text-ink-3">
                    {{ symbol }} · server-side random walk
                </p>
                <div class="mt-1 flex items-baseline gap-3">
                    <!-- Key by history length so each server tick re-renders a fresh node -->
                    <BigNumber :key="history.length" class="text-4xl">
                        ${{ price.toFixed(2) }}
                    </BigNumber>
                    <span
                        v-if="direction !== null"
                        class="font-mono text-sm tabular-nums text-ink-2"
                    >
                        <span aria-hidden="true">{{ direction === "up" ? "▲" : "▼" }}</span>
                        <span class="sr-only">{{ direction === "up" ? "Up" : "Down" }}</span>
                        {{ Math.abs(delta).toFixed(2) }}
                    </span>
                </div>
            </div>

            <div class="flex items-center gap-4">
                <span class="core-status">
                    <span
                        class="core-dot"
                        :data-state="paused ? 'off' : 'live'"
                        aria-hidden="true"
                    />
                    {{ paused ? "Paused" : "Every 2s" }}
                </span>
                <Button
                    variant="secondary"
                    size="sm"
                    :aria-pressed="paused"
                    @click="paused = !paused"
                >
                    {{ paused ? "Resume ticks" : "Pause ticks" }}
                </Button>
            </div>
        </div>

        <Sparkline
            class="mt-6"
            :values="history"
            :direction="direction"
            :aria-label="`Sparkline of the last ${history.length} prices for ${symbol}`"
        />

        <!-- Dimension line spanning the plot: how many ticks it holds. -->
        <div class="mt-2 pl-14">
            <div class="core-dim">
                <span>{{ history.length }} of {{ MAX_POINTS }} points</span>
            </div>
        </div>

        <p class="mt-4 text-xs leading-relaxed text-ink-3">
            <code class="core-code">wire.$call("tick")</code> every 2s.
            <code class="core-code">wire.$watch("price", …)</code>
            streams each change back.
        </p>
    </Panel>
</template>
