// apps/demo-svelte/resources/js/components/ui/Eyebrow.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import type { HTMLAttributes } from "svelte/elements";
    import { cn } from "./cn";

    interface Props extends HTMLAttributes<HTMLSpanElement> {
        children?: Snippet;
    }

    let { children, class: className, ...rest }: Props = $props();
</script>

<!-- The annotation voice (`.k .k--caps`): 11px tracked mono caps. -->
<span
    {...rest}
    class={cn(
        "font-mono text-[0.6875rem] font-normal uppercase leading-normal tracking-[0.1em] text-ink-3",
        className,
    )}
>
    {@render children?.()}
</span>

// apps/demo-react/resources/js/components/ui/Eyebrow.tsx
import React from "react";
import { cn } from "./cn";

/** The annotation voice (`.k .k--caps`): 11px tracked mono caps. */
const Eyebrow: React.FC<React.HTMLAttributes<HTMLSpanElement>> = ({
    className,
    ...rest
}) => (
    <span
        className={cn(
            "font-mono text-[0.6875rem] font-normal uppercase leading-normal tracking-[0.1em] text-ink-3",
            className,
        )}
        {...rest}
    />
);

export default Eyebrow;
