// apps/demo-svelte/resources/js/components/ui/Spinner.svelte
<script lang="ts">
    import type { SVGAttributes } from "svelte/elements";
    import { cn } from "./cn";

    interface Props extends SVGAttributes<SVGSVGElement> {}

    let { class: className, ...rest }: Props = $props();
</script>

<!--
    A line-drawn square with a short stroke tracing its edge. Inherits the
    text color; size it with `w-*`/`h-*`.
-->
<svg
    {...rest}
    class={cn("ui-spinner w-4 h-4 shrink-0", className)}
    viewBox="0 0 16 16"
    fill="none"
    aria-hidden="true"
>
    <rect
        x="1.5"
        y="1.5"
        width="13"
        height="13"
        stroke="currentColor"
        stroke-opacity="0.28"
    />
    <rect
        class="ui-spinner__run"
        x="1.5"
        y="1.5"
        width="13"
        height="13"
        stroke="currentColor"
        stroke-width="1.5"
        stroke-linecap="square"
        pathLength="100"
        stroke-dasharray="24 76"
    />
</svg>

// apps/demo-react/resources/js/components/ui/Spinner.tsx
import React from "react";
import { cn } from "./cn";

/**
 * A line-drawn square with a short stroke tracing its edge. Inherits the
 * text color; size it with `w-*`/`h-*`.
 */
const Spinner: React.FC<{ className?: string }> = ({ className }) => (
    <svg
        className={cn("ui-spinner w-4 h-4 shrink-0", className)}
        viewBox="0 0 16 16"
        fill="none"
        aria-hidden="true"
    >
        <rect
            x="1.5"
            y="1.5"
            width="13"
            height="13"
            stroke="currentColor"
            strokeOpacity="0.28"
        />
        <rect
            className="ui-spinner__run"
            x="1.5"
            y="1.5"
            width="13"
            height="13"
            stroke="currentColor"
            strokeWidth="1.5"
            strokeLinecap="square"
            pathLength={100}
            strokeDasharray="24 76"
        />
    </svg>
);

export default Spinner;
