// apps/demo-svelte/resources/js/mesh/Table/OrdersTable/index.svelte
<script lang="ts">
    import {
        getCoreRowModel,
        getFilteredRowModel,
        getPaginationRowModel,
        getSortedRowModel,
        type Row,
        type SortingState,
    } from "@tanstack/table-core";
    import { useWire } from "@mesh/svelte";
    import { createSvelteTable } from "@/components/demo/Table/svelte-table.svelte";
    import DataTable from "@/components/demo/Table/DataTable.svelte";
    import FilterInput from "@/components/demo/Table/FilterInput.svelte";
    import TablePagination from "@/components/demo/Table/TablePagination.svelte";
    import { buildColumns, type Order } from "./columns";

    interface OrdersTableProps {
        orders: Order[];
    }

    const PAGE_SIZES = [10, 25, 50];

    let { orders }: OrdersTableProps = $props();

    const wire = useWire<{ flagOrder: (id: number) => Promise<void> }>();

    // Table state is plain Svelte state — sorting, filtering, and pagination
    // never leave the browser. Only the flag action talks to the server.
    let sorting = $state<SortingState>([]);
    let globalFilter = $state("");
    let pendingIds = $state.raw<Set<number>>(new Set());

    async function handleFlag(id: number) {
        pendingIds = new Set(pendingIds).add(id);
        try {
            await wire.$call("flagOrder", id);
        } finally {
            const next = new Set(pendingIds);
            next.delete(id);
            pendingIds = next;
        }
    }

    const columns = $derived(
        buildColumns({ onFlag: handleFlag, pendingIds }),
    );

    const table = createSvelteTable({
        get data() {
            return orders;
        },
        get columns() {
            return columns;
        },
        state: {
            get sorting() {
                return sorting;
            },
            get globalFilter() {
                return globalFilter;
            },
        },
        onSortingChange: (updater) => {
            sorting = typeof updater === "function" ? updater(sorting) : updater;
        },
        onGlobalFilterChange: (updater) => {
            globalFilter =
                typeof updater === "function" ? updater(globalFilter) : updater;
        },
        getCoreRowModel: getCoreRowModel(),
        getSortedRowModel: getSortedRowModel(),
        getFilteredRowModel: getFilteredRowModel(),
        getPaginationRowModel: getPaginationRowModel(),
        // Stable row identity across server re-renders, sorts, and pages.
        getRowId: (row) => String(row.id),
        initialState: { pagination: { pageSize: 10 } },
    });

    const filteredCount = $derived(table.getFilteredRowModel().rows.length);

    // Flagged state comes from the server: $call("flagOrder") mutates the
    // Livewire component, and the refreshed `orders` prop re-renders the row
    // with the accent.
    const rowClassName = (row: Row<Order>) => (row.original.flagged ? "bom__flagged" : "");
</script>

<div class="space-y-4">
    <div class="flex flex-wrap items-center justify-between gap-3">
        <FilterInput
            bind:value={globalFilter}
            placeholder="Filter orders…"
            ariaLabel="Filter orders"
        />

        <p class="k k--caps text-ink-3 tabular-nums" aria-live="polite">
            {#if filteredCount === orders.length}
                <span class="text-ink">{orders.length}</span> orders
            {:else}
                <span class="text-ink">{filteredCount}</span> of {orders.length} orders
            {/if}
            <span class="mx-2 text-line-3" aria-hidden="true">·</span>
            sorted, filtered &amp; paged client-side
        </p>
    </div>

    <DataTable {table} {rowClassName}>
        {#snippet empty()}No orders match “{globalFilter}”.{/snippet}
    </DataTable>

    <TablePagination {table} pageSizes={PAGE_SIZES} />
</div>

// apps/demo-react/resources/js/mesh/Table/OrdersTable/index.tsx
import React, { useCallback, useMemo, useState } from "react";
import {
    getCoreRowModel,
    getFilteredRowModel,
    getPaginationRowModel,
    getSortedRowModel,
    useReactTable,
    type SortingState,
} from "@tanstack/react-table";
import { useWire } from "@mesh/react";
import DataTable from "@/components/demo/Table/DataTable";
import FilterInput from "@/components/demo/Table/FilterInput";
import TablePagination from "@/components/demo/Table/TablePagination";
import { buildColumns, type Order } from "./columns";

interface OrdersTableProps {
    orders: Order[];
}

const PAGE_SIZES = [10, 25, 50];

const OrdersTable: React.FC<OrdersTableProps> = ({ orders }) => {
    const wire = useWire<{ flagOrder: (id: number) => Promise<void> }>();

    // Table state is plain React state — sorting, filtering, and pagination
    // never leave the browser. Only the flag action talks to the server.
    const [sorting, setSorting] = useState<SortingState>([]);
    const [globalFilter, setGlobalFilter] = useState("");
    const [pendingIds, setPendingIds] = useState<Set<number>>(new Set());

    const handleFlag = useCallback(
        async (id: number) => {
            setPendingIds((prev) => new Set(prev).add(id));
            try {
                await wire.$call("flagOrder", id);
            } finally {
                setPendingIds((prev) => {
                    const next = new Set(prev);
                    next.delete(id);
                    return next;
                });
            }
        },
        [wire],
    );

    const columns = useMemo(
        () => buildColumns({ onFlag: handleFlag, pendingIds }),
        [handleFlag, pendingIds],
    );

    const table = useReactTable({
        data: orders,
        columns,
        state: { sorting, globalFilter },
        onSortingChange: setSorting,
        onGlobalFilterChange: setGlobalFilter,
        getCoreRowModel: getCoreRowModel(),
        getSortedRowModel: getSortedRowModel(),
        getFilteredRowModel: getFilteredRowModel(),
        getPaginationRowModel: getPaginationRowModel(),
        // Stable row identity across server re-renders, sorts, and pages.
        getRowId: (row) => String(row.id),
        initialState: { pagination: { pageSize: 10 } },
    });

    const filteredCount = table.getFilteredRowModel().rows.length;

    return (
        <div className="space-y-4">
            <div className="flex flex-wrap items-center justify-between gap-3">
                <FilterInput
                    value={globalFilter}
                    onChange={setGlobalFilter}
                    placeholder="Filter orders…"
                    ariaLabel="Filter orders"
                />

                <p className="k k--caps text-ink-3 tabular-nums" aria-live="polite">
                    {filteredCount === orders.length ? (
                        <>
                            <span className="text-ink">{orders.length}</span> orders
                        </>
                    ) : (
                        <>
                            <span className="text-ink">{filteredCount}</span> of {orders.length} orders
                        </>
                    )}
                    <span className="mx-2 text-line-3" aria-hidden="true">
                        ·
                    </span>
                    sorted, filtered &amp; paged client-side
                </p>
            </div>

            <DataTable
                table={table}
                emptyMessage={<>No orders match “{globalFilter}”.</>}
                // Flagged state comes from the server: $call("flagOrder") mutates
                // the Livewire component, and the refreshed `orders` prop re-renders
                // the row with the accent.
                rowClassName={(row) => (row.original.flagged ? "bom__flagged" : "")}
            />

            <TablePagination table={table} pageSizes={PAGE_SIZES} />
        </div>
    );
};

export default OrdersTable;
