// apps/demo-svelte/resources/js/mesh/Table/OrdersTable/index.svelte
<script lang="ts">
    import {
        getCoreRowModel,
        getFilteredRowModel,
        getPaginationRowModel,
        getSortedRowModel,
        type Row,
        type SortingState,
    } from "@tanstack/table-core";
    import { useWire } from "@mesh/svelte";
    import { createSvelteTable } from "@/components/demo/Table/svelte-table.svelte";
    import DataTable from "@/components/demo/Table/DataTable.svelte";
    import FilterInput from "@/components/demo/Table/FilterInput.svelte";
    import TablePagination from "@/components/demo/Table/TablePagination.svelte";
    import { buildColumns, type Order } from "./columns";

    interface OrdersTableProps {
        orders: Order[];
    }

    const PAGE_SIZES = [10, 25, 50];

    let { orders }: OrdersTableProps = $props();

    const wire = useWire<{ flagOrder: (id: number) => Promise<void> }>();

    // Table state is plain Svelte state — sorting, filtering, and pagination
    // never leave the browser. Only the flag action talks to the server.
    let sorting = $state<SortingState>([]);
    let globalFilter = $state("");
    let pendingIds = $state.raw<Set<number>>(new Set());

    async function handleFlag(id: number) {
        pendingIds = new Set(pendingIds).add(id);
        try {
            await wire.$call("flagOrder", id);
        } finally {
            const next = new Set(pendingIds);
            next.delete(id);
            pendingIds = next;
        }
    }

    const columns = $derived(
        buildColumns({ onFlag: handleFlag, pendingIds }),
    );

    const table = createSvelteTable({
        get data() {
            return orders;
        },
        get columns() {
            return columns;
        },
        state: {
            get sorting() {
                return sorting;
            },
            get globalFilter() {
                return globalFilter;
            },
        },
        onSortingChange: (updater) => {
            sorting = typeof updater === "function" ? updater(sorting) : updater;
        },
        onGlobalFilterChange: (updater) => {
            globalFilter =
                typeof updater === "function" ? updater(globalFilter) : updater;
        },
        getCoreRowModel: getCoreRowModel(),
        getSortedRowModel: getSortedRowModel(),
        getFilteredRowModel: getFilteredRowModel(),
        getPaginationRowModel: getPaginationRowModel(),
        // Stable row identity across server re-renders, sorts, and pages.
        getRowId: (row) => String(row.id),
        initialState: { pagination: { pageSize: 10 } },
    });

    const filteredCount = $derived(table.getFilteredRowModel().rows.length);

    // Flagged state comes from the server: $call("flagOrder") mutates the
    // Livewire component, and the refreshed `orders` prop re-renders the row
    // with the accent.
    const rowClassName = (row: Row<Order>) => (row.original.flagged ? "bom__flagged" : "");
</script>

<div class="space-y-4">
    <div class="flex flex-wrap items-center justify-between gap-3">
        <FilterInput
            bind:value={globalFilter}
            placeholder="Filter orders…"
            ariaLabel="Filter orders"
        />

        <p class="k k--caps text-ink-3 tabular-nums" aria-live="polite">
            {#if filteredCount === orders.length}
                <span class="text-ink">{orders.length}</span> orders
            {:else}
                <span class="text-ink">{filteredCount}</span> of {orders.length} orders
            {/if}
            <span class="mx-2 text-line-3" aria-hidden="true">·</span>
            sorted, filtered &amp; paged client-side
        </p>
    </div>

    <DataTable {table} {rowClassName}>
        {#snippet empty()}No orders match “{globalFilter}”.{/snippet}
    </DataTable>

    <TablePagination {table} pageSizes={PAGE_SIZES} />
</div>

// apps/demo-vue/resources/js/mesh/Table/OrdersTable/index.vue
<script setup lang="ts">
import { computed, ref } from "vue";
import {
    getCoreRowModel,
    getFilteredRowModel,
    getPaginationRowModel,
    getSortedRowModel,
    useVueTable,
    type Row,
    type SortingState,
} from "@tanstack/vue-table";
import { useWire } from "@mesh/vue";
import DataTable from "@/components/demo/Table/DataTable.vue";
import FilterInput from "@/components/demo/Table/FilterInput.vue";
import TablePagination from "@/components/demo/Table/TablePagination.vue";
import { buildColumns, type Order } from "./columns";

interface OrdersTableProps {
    orders: Order[];
}

const PAGE_SIZES = [10, 25, 50];

const props = defineProps<OrdersTableProps>();

const wire = useWire<{ flagOrder: (id: number) => Promise<void> }>();

// Table state is plain Vue state — sorting, filtering, and pagination
// never leave the browser. Only the flag action talks to the server.
const sorting = ref<SortingState>([]);
const globalFilter = ref("");
const pendingIds = ref<Set<number>>(new Set());

async function handleFlag(id: number) {
    pendingIds.value = new Set(pendingIds.value).add(id);
    try {
        await wire.$call("flagOrder", id);
    } finally {
        const next = new Set(pendingIds.value);
        next.delete(id);
        pendingIds.value = next;
    }
}

const columns = computed(() =>
    buildColumns({ onFlag: handleFlag, pendingIds: pendingIds.value }),
);

const table = useVueTable({
    get data() {
        return props.orders;
    },
    get columns() {
        return columns.value;
    },
    state: {
        get sorting() {
            return sorting.value;
        },
        get globalFilter() {
            return globalFilter.value;
        },
    },
    onSortingChange: (updater) => {
        sorting.value =
            typeof updater === "function" ? updater(sorting.value) : updater;
    },
    onGlobalFilterChange: (updater) => {
        globalFilter.value =
            typeof updater === "function" ? updater(globalFilter.value) : updater;
    },
    getCoreRowModel: getCoreRowModel(),
    getSortedRowModel: getSortedRowModel(),
    getFilteredRowModel: getFilteredRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    // Stable row identity across server re-renders, sorts, and pages.
    getRowId: (row) => String(row.id),
    initialState: { pagination: { pageSize: 10 } },
});

const filteredCount = computed(() => table.getFilteredRowModel().rows.length);

// Flagged state comes from the server: $call("flagOrder") mutates the
// Livewire component, and the refreshed `orders` prop re-renders the row
// with the accent.
const rowClassName = (row: Row<Order>) => (row.original.flagged ? "bom__flagged" : "");
</script>

<template>
    <div class="space-y-4">
        <div class="flex flex-wrap items-center justify-between gap-3">
            <FilterInput
                v-model="globalFilter"
                placeholder="Filter orders…"
                aria-label="Filter orders"
            />

            <p class="k k--caps text-ink-3 tabular-nums" aria-live="polite">
                <template v-if="filteredCount === orders.length">
                    <span class="text-ink">{{ orders.length }}</span> orders
                </template>
                <template v-else>
                    <span class="text-ink">{{ filteredCount }}</span> of {{ orders.length }} orders
                </template>
                <span class="mx-2 text-line-3" aria-hidden="true">·</span>
                sorted, filtered &amp; paged client-side
            </p>
        </div>

        <DataTable :table="table" :row-class-name="rowClassName">
            <template #empty>No orders match “{{ globalFilter }}”.</template>
        </DataTable>

        <TablePagination :table="table" :page-sizes="PAGE_SIZES" />
    </div>
</template>
